import { Category, Product, Review } from './types';

export const SEED_CATEGORIES: Category[] = [
  {
    id: 'c1111111-1111-1111-1111-111111111111',
    name: 'Herbal Wellness',
    slug: 'herbal-wellness',
    description: 'Time-tested Ayurvedic herbs and potent extracts for holistic vitality and daily balance.',
    image_url: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'c2222222-2222-2222-2222-222222222222',
    name: 'Natural Skincare',
    slug: 'natural-skincare',
    description: 'Clean, toxin-free botanical skincare crafted to nourish and rejuvenate your natural glow.',
    image_url: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'c3333333-3333-3333-3333-333333333333',
    name: 'Hair Care',
    slug: 'hair-care',
    description: 'Pure herbal oils and cleansers infused with ancient herbs for root-to-tip nourishment.',
    image_url: 'https://images.unsplash.com/photo-1608248597359-59754f9a0c7c?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'c4444444-4444-4444-4444-444444444444',
    name: 'Healthy Nutrition',
    slug: 'healthy-nutrition',
    description: '100% plant-based organic superfoods, cold-pressed oils, and farm-fresh nutrition.',
    image_url: 'https://images.unsplash.com/photo-1505576399279-565b52d4ac71?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'c5555555-5555-5555-5555-555555555555',
    name: 'Daily Essentials',
    slug: 'daily-essentials',
    description: 'Gentle, chemical-conscious daily wellness solutions for you and your whole family.',
    image_url: 'https://images.unsplash.com/photo-1512290900672-1f41bf527ba7?auto=format&fit=crop&w=800&q=80',
  },
];

export const SEED_PRODUCTS: Product[] = [
  {
    id: 'p1111111-1111-1111-1111-111111111111',
    name: 'Organic Moringa Superfood Powder',
    slug: 'organic-moringa-powder',
    short_description: 'Nutrient-dense superfood powder packed with vitamins, antioxidants, and plant protein for natural daily energy.',
    description: 'Sourced from certified organic farms, our pure Moringa Oleifera Leaf Powder is shade-dried to lock in maximum bioactive phytonutrients. Often celebrated as the "Miracle Tree", Moringa contains over 90 nutrients and 46 antioxidants to combat oxidative stress, revitalize stamina, and support natural metabolic balance.',
    category_id: 'c4444444-4444-4444-4444-444444444444',
    category: SEED_CATEGORIES[3],
    price: 449,
    original_price: 599,
    stock: 85,
    featured: true,
    is_active: true,
    benefits: 'Boosts daily energy levels naturally; Supports immune defense and cellular detox; Enhances digestion and gut microbiome balance; 100% Raw, Vegan, and Non-GMO',
    ingredients: '100% Certified Pure Organic Moringa Leaf (Moringa oleifera) Powder. No preservatives, artificial colors, or binders.',
    how_to_use: 'Mix 1 teaspoon (approx. 5g) into warm water, morning smoothies, fresh green juices, or sprinkle over salads. Best consumed in the morning.',
    images: [
      'https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1505576399279-565b52d4ac71?auto=format&fit=crop&w=800&q=80',
    ],
    rating: 4.9,
    review_count: 128,
  },
  {
    id: 'p2222222-2222-2222-2222-222222222222',
    name: 'Herbal Immunity Boost Tablets',
    slug: 'herbal-immunity-tablets',
    short_description: 'Potent Ayurvedic blend of Giloy, Tulsi, Amla, and Curcumin for powerful all-weather immune resilience.',
    description: 'Our Herbal Immunity Tablets combine centuries-old Rasayana herbs crafted into convenient daily tablets. Formulated with high-potency standardized extracts of Giloy, Holy Basil (Tulsi), Vitamin C-rich Amla, and 95% Curcuminoids to build deep, sustainable cellular immunity and defend against seasonal pollutants.',
    category_id: 'c1111111-1111-1111-1111-111111111111',
    category: SEED_CATEGORIES[0],
    price: 499,
    original_price: 699,
    stock: 120,
    featured: true,
    is_active: true,
    benefits: 'Strengthens immune cell response; Helps relieve respiratory discomfort and seasonal allergies; Promotes healthy inflammatory balance; Rich in natural bio-available Vitamin C',
    ingredients: 'Organic Giloy (Tinospora cordifolia) Extract, Holy Basil (Ocimum sanctum) Extract, Amla (Phyllanthus emblica) Fruit Extract, Curcumin Extract (95%), Piperine (Black Pepper Extract).',
    how_to_use: 'Take 1 tablet twice daily with lukewarm water after meals, or as directed by your Ayurvedic healthcare practitioner.',
    images: [
      'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1584017911766-d451b3d0e843?auto=format&fit=crop&w=800&q=80',
    ],
    rating: 4.8,
    review_count: 94,
  },
  {
    id: 'p3333333-3333-3333-3333-333333333333',
    name: 'Pure Aloe Vera Gentle Face Cleanser',
    slug: 'aloe-vera-face-cleanser',
    short_description: 'Sulfate-free soothing facial cleanser with cold-pressed organic aloe vera and calming chamomile extract.',
    description: 'Wash away dirt, pollutants, and excess oil without stripping your skin’s vital lipid barrier. Formulated with 80% fresh organic Aloe Vera inner leaf gel, soothing German Chamomile, and botanical surfactants for soft, refreshed, and balanced skin.',
    category_id: 'c2222222-2222-2222-2222-222222222222',
    category: SEED_CATEGORIES[1],
    price: 349,
    original_price: 449,
    stock: 64,
    featured: true,
    is_active: true,
    benefits: 'Gently purifies pores without moisture loss; Calms redness, irritation, and sensitivity; Restores skin pH balance (5.5); Free from SLS, SLES, parabens, and synthetic fragrance',
    ingredients: 'Organic Aloe Barbadensis Leaf Juice, Coco-Glucoside, Vegetable Glycerin, Chamomilla Recutita (Chamomile) Flower Extract, Green Tea Leaf Extract, Provitamin B5 (Panthenol).',
    how_to_use: 'Apply a coin-sized pump to damp face. Gently massage in upward circular motions for 60 seconds. Rinse thoroughly with cool or lukewarm water. Pat dry with a clean towel.',
    images: [
      'https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?auto=format&fit=crop&w=800&q=80',
    ],
    rating: 4.9,
    review_count: 145,
  },
  {
    id: 'p4444444-4444-4444-4444-444444444444',
    name: 'Cold Pressed Virgin Coconut Oil',
    slug: 'cold-pressed-coconut-oil',
    short_description: '100% raw, unrefined cold-pressed coconut oil for nourishing deep hair conditioning and body hydration.',
    description: 'Extracted from fresh, mature organic coconuts using traditional wooden expeller (Kachi Ghani) cold-pressing techniques. This retains the rich medium-chain triglycerides (MCTs) including Lauric acid, delivering a heavenly natural aroma and luxurious conditioning for hair, scalp, and skin.',
    category_id: 'c4444444-4444-4444-4444-444444444444',
    category: SEED_CATEGORIES[3],
    price: 399,
    original_price: 499,
    stock: 90,
    featured: true,
    is_active: true,
    benefits: 'Deeply penetrates hair shafts to reduce protein loss; Nourishes dry scalp and helps prevent dandruff; Ultra-hydrating natural body moisturizer; Edible grade and 100% chemical free',
    ingredients: '100% Pure Cold Pressed Virgin Coconut (Cocos nucifera) Oil. Zero additives, zero heat processing.',
    how_to_use: 'Warm a small amount between your palms. For Hair: Gently massage into scalp and ends 1-2 hours before washing. For Skin: Apply right after showering to seal in moisture.',
    images: [
      'https://images.unsplash.com/photo-1526947425960-945c6e72858f?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&w=800&q=80',
    ],
    rating: 4.7,
    review_count: 82,
  },
  {
    id: 'p5555555-5555-5555-5555-555555555555',
    name: 'Herbal Hair Growth & Vitality Oil',
    slug: 'herbal-hair-growth-oil',
    short_description: 'Traditional Kshirpak formulation with Bhringraj, Rosemary, Brahmi, and Amla for stronger, denser hair roots.',
    description: 'Infused through an authentic 21-day slow decoction process, this restorative Ayurvedic hair oil brings together Bhringraj (the king of hair), stimulating Rosemary oil, Brahmi, and cold-pressed Sesame oil to revitalize dormant follicles, reduce shedding, and promote thick, lustrous growth.',
    category_id: 'c3333333-3333-3333-3333-333333333333',
    category: SEED_CATEGORIES[2],
    price: 599,
    original_price: 799,
    stock: 45,
    featured: true,
    is_active: true,
    benefits: 'Stimulates micro-circulation at the hair roots; Significantly minimizes hair breakage and split ends; Delays premature greying naturally; Leaves hair silky and manageable',
    ingredients: 'Bhringraj (Eclipta alba), Brahmi (Bacopa monnieri), Amla (Emblica officinalis), Rosemary Essential Oil, Methi (Fenugreek) Seed Extract, Cold Pressed Sesame Oil, Castor Oil.',
    how_to_use: 'Apply generously to scalp using the root applicator. Massage gently with fingertips in circular motions for 5 to 10 minutes. Leave on overnight or for minimum 2 hours before shampooing.',
    images: [
      'https://images.unsplash.com/photo-1608248597359-59754f9a0c7c?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1601049541289-9b1b7bbbfe19?auto=format&fit=crop&w=800&q=80',
    ],
    rating: 4.9,
    review_count: 210,
  },
  {
    id: 'p6666666-6666-6666-6666-666666666666',
    name: 'Organic Turmeric Curcumin 95% Capsules',
    slug: 'organic-turmeric-capsules',
    short_description: 'High-potency organic turmeric with 95% standardized curcumin and black pepper extract for joint and cellular vitality.',
    description: 'Harvested from certified organic farms in the foothills of India, our Turmeric capsules combine full-spectrum turmeric rhizome with 95% standardized Curcumin extract. Enriched with BioPerine (Black Pepper Extract) to enhance curcumin absorption by up to 2000%.',
    category_id: 'c1111111-1111-1111-1111-111111111111',
    category: SEED_CATEGORIES[0],
    price: 549,
    original_price: 749,
    stock: 70,
    featured: true,
    is_active: true,
    benefits: 'Supports joint mobility and flexibility; Powerful antioxidant support against free radicals; Promotes glowing skin and healthy cardiovascular function; Enhanced absorption formula',
    ingredients: 'Organic Curcuma Longa (Turmeric) Root Powder (500mg), Standardized Curcuminoids 95% (200mg), BioPerine Black Pepper Extract (5mg), Plant Cellulose Capsule.',
    how_to_use: 'Take 1 capsule twice daily with meals or a healthy fat source (such as milk or coconut oil) for optimal bioavailability.',
    images: [
      'https://images.unsplash.com/photo-1615485290382-441e4d049cb5?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1584017911766-d451b3d0e843?auto=format&fit=crop&w=800&q=80',
    ],
    rating: 4.8,
    review_count: 76,
  },
  {
    id: 'p7777777-7777-7777-7777-777777777777',
    name: 'KSM-66 Organic Ashwagandha Root',
    slug: 'ksm-66-ashwagandha-capsules',
    short_description: 'Full-spectrum root extract designed to balance cortisol, ease daily stress, and improve restful sleep quality.',
    description: 'KSM-66 is the highest concentration full-spectrum root extract available today. Our formula helps modulate stress response, support cognitive clarity, and foster deep restorative rest without daytime drowsiness.',
    category_id: 'c1111111-1111-1111-1111-111111111111',
    category: SEED_CATEGORIES[0],
    price: 649,
    original_price: 899,
    stock: 55,
    featured: false,
    is_active: true,
    benefits: 'Helps regulate cortisol and stress hormones; Promotes deep, uninterrupted sleep; Boosts cognitive endurance and vitality; Clinically researched adaptogen',
    ingredients: 'KSM-66 Organic Ashwagandha (Withania somnifera) Root Extract (600mg, standardized to 5% withanolides), Vegetarian Capsule.',
    how_to_use: 'Take 1 capsule in the evening with warm milk or water 30 minutes before bedtime.',
    images: [
      'https://images.unsplash.com/photo-1512290900672-1f41bf527ba7?auto=format&fit=crop&w=800&q=80',
    ],
    rating: 4.9,
    review_count: 112,
  },
  {
    id: 'p8888888-8888-8888-8888-888888888888',
    name: 'Pure Hydro-Distilled Rose Water Toner',
    slug: 'pure-rose-water-toner',
    short_description: 'Steam-distilled pure Rosa Damascena mist to hydrate, tone, and balance skin pH with zero alcohol.',
    description: 'Crafted from early morning hand-picked Kannauj Damask roses, this alcohol-free mist delivers instant botanical hydration, shrinks open pores, and revitalizes tired skin throughout the day.',
    category_id: 'c2222222-2222-2222-2222-222222222222',
    category: SEED_CATEGORIES[1],
    price: 299,
    original_price: 399,
    stock: 110,
    featured: false,
    is_active: true,
    benefits: 'Instantly hydrates and tightens enlarged pores; Balances skin natural pH; Alcohol-free, preservative-free, 100% natural; Multi-use as makeup setting spray or face refresher',
    ingredients: '100% Pure Steam Distilled Damask Rose (Rosa damascena) Floral Hydrosol.',
    how_to_use: 'Spray evenly across face and neck after cleansing or whenever your skin feels dry or fatigued. Allow to air dry.',
    images: [
      'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?auto=format&fit=crop&w=800&q=80',
    ],
    rating: 4.8,
    review_count: 88,
  },
  {
    id: 'p9999999-9999-9999-9999-999999999999',
    name: 'Organic Wild Forest Raw Honey',
    slug: 'wild-forest-raw-honey',
    short_description: 'Unprocessed, unheated, single-origin raw honey harvested sustainably from deep Himalayan forests.',
    description: 'Unlike commercially processed syrups, our Raw Forest Honey is cold-extracted without boiling or ultra-filtering, preserving all naturally occurring enzymes, pollen, propolis, and essential minerals.',
    category_id: 'c4444444-4444-4444-4444-444444444444',
    category: SEED_CATEGORIES[3],
    price: 429,
    original_price: 549,
    stock: 60,
    featured: false,
    is_active: true,
    benefits: 'Rich in live enzymes and bio-active pollen; Natural immune tonic and throat soothing elixir; Zero added sugar, zero corn syrup, zero adulteration; Delicious rich floral taste',
    ingredients: '100% Pure Wild Forest Raw Honey.',
    how_to_use: 'Enjoy 1 tablespoon straight, or stir into warm herbal tea, lemon water, breakfast oats, or desserts. Do not boil.',
    images: [
      'https://images.unsplash.com/photo-1587049352846-4a222e784d38?auto=format&fit=crop&w=800&q=80',
    ],
    rating: 5.0,
    review_count: 67,
  },
  {
    id: 'paaaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',
    name: 'Organic Wild Amla & Bhringraj Shampoo Bar',
    slug: 'amla-bhringraj-shampoo-bar',
    short_description: 'Zero-plastic solid hair cleanser enriched with Shikakai, Reetha, and nourishing botanical oils.',
    description: 'Switch to clean hair care with our concentrated herbal shampoo bar. Lathers luxuriously into a rich foam that gently lifts away grease while infusing hair with nourishing Amla tannins and strengthening Bhringraj.',
    category_id: 'c3333333-3333-3333-3333-333333333333',
    category: SEED_CATEGORIES[2],
    price: 279,
    original_price: 349,
    stock: 80,
    featured: false,
    is_active: true,
    benefits: 'Equates to 3 liquid shampoo bottles (Zero plastic waste); Gently balances scalp microbiome without harsh sulfates; Conditions hair strands naturally with Shikakai; Compact and travel friendly',
    ingredients: 'Sodium Cocoyl Isethionate, Organic Amla Fruit Powder, Bhringraj Leaf Extract, Shikakai Powder, Reetha Fruit Extract, Shea Butter, Sweet Almond Oil.',
    how_to_use: 'Rub wet bar between hands or directly onto wet scalp until rich lather forms. Massage gently into scalp and hair. Rinse clean.',
    images: [
      'https://images.unsplash.com/photo-1607006314144-8622ff6fa2c0?auto=format&fit=crop&w=800&q=80',
    ],
    rating: 4.7,
    review_count: 53,
  },
];

export const SEED_REVIEWS: Review[] = [
  {
    id: 'r1',
    product_id: 'p1111111-1111-1111-1111-111111111111',
    customer_name: 'Priya Sharma',
    rating: 5,
    comment: 'The quality is unmatched! I mix a spoon into my morning smoothie every day and notice a clear boost in my energy without the caffeine crash.',
    verified_purchase: true,
    created_at: '2026-02-15T10:00:00Z',
  },
  {
    id: 'r2',
    product_id: 'p2222222-2222-2222-2222-222222222222',
    customer_name: 'Rohan Mehta',
    rating: 5,
    comment: 'Essential for changing weather. Since taking these Giloy & Amla tablets, my seasonal allergies are virtually gone. Truly authentic formulation.',
    verified_purchase: true,
    created_at: '2026-02-18T14:30:00Z',
  },
  {
    id: 'r3',
    product_id: 'p3333333-3333-3333-3333-333333333333',
    customer_name: 'Ananya Iyer',
    rating: 5,
    comment: 'So soothing on sensitive skin! Doesn\'t dry my face at all. Truly authentic aloe feel with a subtle natural botanical aroma.',
    verified_purchase: true,
    created_at: '2026-02-20T09:15:00Z',
  },
  {
    id: 'r4',
    product_id: 'p5555555-5555-5555-5555-555555555555',
    customer_name: 'Devika Nair',
    rating: 5,
    comment: 'My hair fall decreased noticeably in just 3 weeks of using this Bhringraj oil. Scalp feels nourished, cool, and healthy.',
    verified_purchase: true,
    created_at: '2026-02-22T16:45:00Z',
  },
  {
    id: 'r5',
    product_id: 'p6666666-6666-6666-6666-666666666666',
    customer_name: 'Amitabh Verma',
    rating: 5,
    comment: 'High grade turmeric with black pepper extract. Excellent for post-workout joint stiffness and general well-being.',
    verified_purchase: true,
    created_at: '2026-02-24T11:20:00Z',
  },
];
