import { Category, Product, Review } from './types';

export const SEED_CATEGORIES: Category[] = [
  {
    id: 'c1111111-1111-1111-1111-111111111111',
    name: 'Herbal Skincare',
    slug: 'herbal-skincare',
    description: 'Handcrafted botanical facial cleansers, nourishing night creams, and clarifying herbal soaps.',
    image_url: '/images/categories/herbal-skincare.jpg',
  },
  {
    id: 'c2222222-2222-2222-2222-222222222222',
    name: 'Hair Care',
    slug: 'hair-care',
    description: 'Traditional herbal hair oils, root-strengthening shampoos, and botanical conditioners.',
    image_url: '/images/categories/hair-care.jpg',
  },
  {
    id: 'c3333333-3333-3333-3333-333333333333',
    name: 'Natural Bath & Body',
    slug: 'bath-and-body',
    description: 'Cold-processed artisanal bath bars, calming body washes, and restorative body lotions.',
    image_url: '/images/categories/bath-and-body.jpg',
  },
  {
    id: 'c4444444-4444-4444-4444-444444444444',
    name: 'Organic Essentials',
    slug: 'organic-essentials',
    description: 'Cold-pressed virgin coconut oils, pure aloe vera gels, and multi-purpose botanical care.',
    image_url: '/images/categories/organic-essentials.jpg',
  },
  {
    id: 'c5555555-5555-5555-5555-555555555555',
    name: 'Natural Wellness',
    slug: 'natural-wellness',
    description: 'Authentic Ayurvedic herbal bath powders, traditional ubtans, and soothing botanicals.',
    image_url: '/images/categories/natural-wellness.jpg',
  },
];

export const SEED_PRODUCTS: Product[] = [
  {
    id: 'p1111111-1111-1111-1111-111111111111',
    name: 'Neem & Tulsi Herbal Soap',
    slug: 'neem-tulsi-herbal-soap',
    short_description: 'Handcrafted herbal cleansing bar infused with pure neem and sacred tulsi for clean, refreshed skin.',
    description: 'Handmade using traditional cold-process soapmaking, this cleansing bar blends organic neem leaf extract, sacred tulsi, and cold-pressed coconut oil. Produces a creamy, rich lather that gently purifies skin pores without stripping natural moisture, leaving your skin feeling balanced, invigorated, and clear.',
    category_id: 'c1111111-1111-1111-1111-111111111111',
    category: SEED_CATEGORIES[0],
    price: 149,
    original_price: 199,
    stock: 65,
    featured: true,
    is_active: true,
    benefits: 'Gentle everyday cleansing; Leaves skin refreshed and clarified; Made with pure saponified vegetable oils; 100% biodegradable and chemical-conscious',
    ingredients: 'Saponified Coconut Oil, Neem Leaf Extract (Azadirachta indica), Holy Basil (Tulsi) Oil, Castor Oil, Vegetable Glycerin, Pure Essential Oil Blend.',
    how_to_use: 'Lather with warm water between hands or with a natural washcloth. Massage gently over face and body, then rinse clean.',
    images: [
      '/images/products/neem-tulsi-soap.jpg',
    ],
    rating: 4.9,
    review_count: 84,
  },
  {
    id: 'p2222222-2222-2222-2222-222222222222',
    name: 'Aloe Vera Gentle Face Wash',
    slug: 'aloe-vera-face-wash',
    short_description: 'Mild, sulfate-free botanical face cleanser enriched with organic aloe vera and cucumber extract.',
    description: 'A gentle daily cleanser formulated for sensitive and dry skin types. Packed with fresh organic aloe barbadensis leaf juice, calming cucumber extract, and pure rose hydrosol. Gently lifts away daily dirt, excess sebum, and environmental grime while preserving your skin vital moisture barrier.',
    category_id: 'c1111111-1111-1111-1111-111111111111',
    category: SEED_CATEGORIES[0],
    price: 249,
    original_price: 349,
    stock: 50,
    featured: true,
    is_active: true,
    benefits: 'Non-drying, sulfate-free daily cleansing; Deeply hydrates and calms sensitive skin; Balances skin pH naturally; Clean, residue-free rinse',
    ingredients: 'Organic Aloe Vera Leaf Juice, Cucumber Fruit Extract, Rose Damascena Distillate, Coco-Glucoside (plant surfactant), Vegetable Glycerin, Vitamin E.',
    how_to_use: 'Apply 1-2 pumps onto damp face and neck. Gently massage in upward circular motions for 30 seconds. Rinse thoroughly with water.',
    images: [
      '/images/products/aloe-face-wash.jpg',
    ],
    rating: 4.8,
    review_count: 62,
  },
  {
    id: 'p3333333-3333-3333-3333-333333333333',
    name: 'Rose & Sandalwood Night Cream',
    slug: 'rose-sandalwood-night-cream',
    short_description: 'Rich botanical night cream designed for deep overnight hydration and radiant morning skin.',
    description: 'An intensely restorative night moisturizing balm infused with authentic Mysore sandalwood distillate and steam-distilled Indian damask rose. Works in harmony with your skin natural nocturnal rejuvenation cycle to deliver deep hydration, restore elasticity, and impart a smooth, velvety texture by morning.',
    category_id: 'c1111111-1111-1111-1111-111111111111',
    category: SEED_CATEGORIES[0],
    price: 449,
    original_price: 599,
    stock: 42,
    featured: true,
    is_active: true,
    benefits: 'Deep overnight moisture replenishment; Softens fine lines and rough patches; Calming natural botanical aroma; Free from mineral oils and silicones',
    ingredients: 'Pure Sandalwood Hydrosol, Damask Rose Extract, Shea Butter, Cold-Pressed Sweet Almond Oil, Jojoba Seed Oil, Olive Squalane, Vitamin E.',
    how_to_use: 'After evening cleansing, warm a pea-sized amount between fingertips and gently press into face, neck, and decolletage.',
    images: [
      '/images/products/rose-sandalwood-cream.jpg',
    ],
    rating: 5.0,
    review_count: 91,
  },
  {
    id: 'p4444444-4444-4444-4444-444444444444',
    name: 'Turmeric Glow Face Cream',
    slug: 'turmeric-glow-face-cream',
    short_description: 'Lightweight daytime moisturizing cream infused with wild turmeric and saffron extract.',
    description: 'Crafted with wild Kasturi Manjal (aromatic turmeric) and Kashmiri saffron threads, this lightweight day cream provides non-greasy daily hydration. Helps promote a naturally radiant complexion while protecting skin against daily environmental elements.',
    category_id: 'c1111111-1111-1111-1111-111111111111',
    category: SEED_CATEGORIES[0],
    price: 379,
    original_price: 499,
    stock: 38,
    featured: false,
    is_active: true,
    benefits: 'Promotes natural skin radiance and clarity; Lightweight and non-comedogenic; Absorbs quickly with no yellow staining; Perfect daily moisture under makeup',
    ingredients: 'Wild Turmeric (Curcuma aromatica) Extract, Kashmiri Saffron Stigmas, Aloe Vera Gel, Almond Oil, Niacinamide, Glycerin, Stearic Acid.',
    how_to_use: 'Apply evenly to clean face and neck each morning. Massage in circular motions until absorbed.',
    images: [
      '/images/products/turmeric-face-cream.jpg',
    ],
    rating: 4.8,
    review_count: 47,
  },
  {
    id: 'p5555555-5555-5555-5555-555555555555',
    name: 'Amla & Bhringraj Hair Oil',
    slug: 'amla-bhringraj-hair-oil',
    short_description: 'Traditional Ayurvedic herbal hair oil slowly infused with fresh amla and bhringraj leaves.',
    description: 'Prepared using traditional slow infusion, fresh Amla (Indian Gooseberry) and Bhringraj leaves are gently cooked in pure cold-pressed sesame and virgin coconut oils. Delivers vital nutrients directly to hair follicles, calms the scalp, reduces dryness, and leaves strands smooth and lustrous.',
    category_id: 'c2222222-2222-2222-2222-222222222222',
    category: SEED_CATEGORIES[1],
    price: 349,
    original_price: 449,
    stock: 55,
    featured: true,
    is_active: true,
    benefits: 'Strengthens roots and reduces strand breakage; Conditions scalp and relieves flakiness; 100% pure herbal infusion with zero mineral oil; Traditional Ayurvedic formulation',
    ingredients: 'Cold-Pressed Sesame Oil, Virgin Coconut Oil, Bhringraj (Eclipta alba) Extract, Amla Fruit Extract, Brahmi, Fenugreek Seed Oil, Rosemary Essential Oil.',
    how_to_use: 'Warm a few drops in your hands. Gently massage into scalp using circular fingertip motions. Leave on for at least 1 hour or overnight before shampooing.',
    images: [
      '/images/products/amla-bhringraj-oil.jpg',
    ],
    rating: 4.9,
    review_count: 112,
  },
  {
    id: 'p6666666-6666-6666-6666-666666666666',
    name: 'Herbal Neem & Shikakai Shampoo',
    slug: 'herbal-neem-shikakai-shampoo',
    short_description: 'Clarifying botanical hair cleanser crafted with shikakai, reetha, and antibacterial neem.',
    description: 'A gentle, plant-powered shampoo combining natural soapnuts (Reetha), conditioning Shikakai pods, and antibacterial Neem leaf. Effectively cleanses the scalp of sweat, dirt, and pollution without stripping natural protective oils, leaving hair clean, bouncy, and manageable.',
    category_id: 'c2222222-2222-2222-2222-222222222222',
    category: SEED_CATEGORIES[1],
    price: 289,
    original_price: 379,
    stock: 60,
    featured: true,
    is_active: true,
    benefits: 'Mild, sulfate-free scalp clarifying; Enriched with natural saponins from soapnuts; Soothes itchy or sensitive scalp; Leaves hair soft, shiny, and tangle-free',
    ingredients: 'Shikakai Pod Extract, Reetha (Soapnut) Extract, Neem Leaf Water, Aloe Vera Juice, Plant Glucoside Surfactants, Peppermint Essential Oil.',
    how_to_use: 'Apply onto wet hair and scalp. Massage gently to work up a rich lather. Rinse thoroughly with lukewarm water.',
    images: [
      '/images/products/neem-shikakai-shampoo.jpg',
    ],
    rating: 4.7,
    review_count: 58,
  },
  {
    id: 'p7777777-7777-7777-7777-777777777777',
    name: 'Hibiscus & Fenugreek Conditioner',
    slug: 'hibiscus-fenugreek-conditioner',
    short_description: 'Deeply moisturizing herbal conditioner with red hibiscus petals and conditioning fenugreek.',
    description: 'Rich in natural botanical mucilage from fresh hibiscus flowers and soaked fenugreek seeds, this silicone-free conditioner softens rough cuticles, detangles knotty hair, and locks in vital moisture without weighing hair down.',
    category_id: 'c2222222-2222-2222-2222-222222222222',
    category: SEED_CATEGORIES[1],
    price: 329,
    original_price: 429,
    stock: 40,
    featured: false,
    is_active: true,
    benefits: 'Effortless detangling and frizz control; Seals split ends and boosts natural shine; Silicone-free and safe for color-treated hair; Pleasant botanical floral aroma',
    ingredients: 'Hibiscus Flower Water, Fenugreek Seed Extract, Argan Kernel Oil, Shea Butter, Plant-derived Cetearyl Alcohol, Sweet Orange Oil.',
    how_to_use: 'After washing, apply to mid-lengths and ends of damp hair. Leave for 2 to 3 minutes, then rinse thoroughly.',
    images: [
      '/images/products/hibiscus-conditioner.jpg',
    ],
    rating: 4.8,
    review_count: 39,
  },
  {
    id: 'p8888888-8888-8888-8888-888888888888',
    name: 'Sandalwood Handmade Bath Bar',
    slug: 'sandalwood-handmade-bath-bar',
    short_description: 'Cold-processed artisanal bath soap made with real sandalwood powder and nourishing butter.',
    description: 'Handcrafted in small artisanal batches with ground Mysore sandalwood powder and pure vegetable oils. Aged naturally for 4 weeks to create a dense, long-lasting bar with a luxurious creamy foam and authentic woody fragrance that calms the senses.',
    category_id: 'c3333333-3333-3333-3333-333333333333',
    category: SEED_CATEGORIES[2],
    price: 189,
    original_price: 249,
    stock: 72,
    featured: true,
    is_active: true,
    benefits: 'Rich, creamy lather that moisturizes dry skin; Genuine Mysore sandalwood fragrance; Free from animal fats, parabens, and sulfates; Gentle for whole-family daily baths',
    ingredients: 'Saponified Coconut Oil, Olive Oil, Sandalwood Wood Powder, Raw Shea Butter, Cocoa Butter, Pure Sandalwood Essential Oil.',
    how_to_use: 'Rub the wet bar over skin or a loofah to create a rich lather. Cleanse gently and rinse thoroughly.',
    images: [
      '/images/products/sandalwood-bath-bar.jpg',
    ],
    rating: 4.9,
    review_count: 96,
  },
  {
    id: 'p9999999-9999-9999-9999-999999999999',
    name: 'Aloe Vera & Rose Body Lotion',
    slug: 'aloe-rose-body-lotion',
    short_description: 'Lightweight, non-sticky daily body moisturizer with fresh aloe vera gel and damask rose water.',
    description: 'A lightweight daily body lotion blending pure organic aloe vera gel with steam-distilled damask rose water and almond oil. Glides effortlessly onto skin, absorbing within seconds without any sticky residue, keeping skin hydrated, calm, and supple throughout the day.',
    category_id: 'c3333333-3333-3333-3333-333333333333',
    category: SEED_CATEGORIES[2],
    price: 349,
    original_price: 449,
    stock: 48,
    featured: false,
    is_active: true,
    benefits: '24-hour non-greasy hydration; Fast absorption with zero stickiness; Delicately scented with natural rose petals; Ideal for all skin types and tropical climates',
    ingredients: 'Organic Aloe Vera Leaf Juice, Rose Flower Water, Sweet Almond Oil, Vegetable Glycerin, Caprylic/Capric Triglycerides, Vitamin E.',
    how_to_use: 'Apply generously across the body immediately after showering while skin is slightly damp. Massage gently until fully absorbed.',
    images: [
      '/images/products/aloe-rose-lotion.jpg',
    ],
    rating: 4.8,
    review_count: 52,
  },
  {
    id: 'paaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',
    name: 'Cold-Pressed Virgin Coconut Oil',
    slug: 'cold-pressed-coconut-oil',
    short_description: '100% pure raw unrefined coconut oil extracted from fresh organic coconuts for skin and hair care.',
    description: 'Extracted without heat from fresh organic coconut meat, our extra virgin coconut oil preserves natural medium-chain fatty acids (lauric acid) and fresh coconut aroma. An all-in-one multipurpose staple for deep hair conditioning, body massage, and natural moisturizing.',
    category_id: 'c4444444-4444-4444-4444-444444444444',
    category: SEED_CATEGORIES[3],
    price: 279,
    original_price: 349,
    stock: 90,
    featured: true,
    is_active: true,
    benefits: '100% Raw, unrefined, and cold-pressed; Multipurpose: hair oil, body hydrator, makeup remover; Zero artificial additives, chemical bleaching, or hexane; Retains authentic tropical aroma',
    ingredients: '100% Pure Organic Cold-Pressed Extra Virgin Coconut (Cocos nucifera) Oil.',
    how_to_use: 'Use as a pre-wash hair mask, all-over body massage oil, or dry skin moisturizer. Liquefies naturally above 24 deg C.',
    images: [
      '/images/products/virgin-coconut-oil.jpg',
    ],
    rating: 5.0,
    review_count: 128,
  },
  {
    id: 'pbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb',
    name: 'Pure Botanical Aloe Vera Gel',
    slug: 'pure-aloe-vera-gel',
    short_description: '99% pure multi-purpose soothing gel harvested from organically grown aloe barbadensis leaves.',
    description: 'Harvested from mature organic aloe leaves, this multi-purpose clear soothing gel provides instant cooling hydration for sun-exposed skin, facial redness, shaving irritation, and dry hair strands. Completely free from artificial green dyes, perfumes, and sticky polymers.',
    category_id: 'c4444444-4444-4444-4444-444444444444',
    category: SEED_CATEGORIES[3],
    price: 219,
    original_price: 299,
    stock: 70,
    featured: false,
    is_active: true,
    benefits: 'Instant cooling and hydration for face and body; Soothes sun-exposed, irritated, or freshly shaved skin; Lightweight oil-free moisture; Clear, fragrance-free formula',
    ingredients: 'Organic Aloe Barbadensis Leaf Juice (99%), Xanthan Gum, Citric Acid, Potassium Sorbate.',
    how_to_use: 'Apply generously to face, body, or scalp as needed. Can be used as a lightweight moisturizer, sleeping mask, or post-sun soother.',
    images: [
      '/images/products/pure-aloe-gel.jpg',
    ],
    rating: 4.9,
    review_count: 77,
  },
  {
    id: 'pccccccc-cccc-cccc-cccc-cccccccccccc',
    name: 'Traditional Herbal Ubtan Bath Powder',
    slug: 'herbal-ubtan-bath-powder',
    short_description: 'Authentic soap-free Ayurvedic herbal bath powder made with gram flour, wild turmeric, and neem.',
    description: 'A traditional soap-free Ayurvedic body cleanser and polishing blend made from stone-ground chickpea flour, fragrant Kasturi Manjal, neem leaves, dried rose petals, and vetiver roots. Gently exfoliates dead skin cells, softens texture, and leaves your skin glowing and radiant.',
    category_id: 'c5555555-5555-5555-5555-555555555555',
    category: SEED_CATEGORIES[4],
    price: 259,
    original_price: 349,
    stock: 45,
    featured: true,
    is_active: true,
    benefits: '100% Soap-free gentle skin polishing; Natural herbal exfoliation for smooth, soft skin; Traditional Ayurvedic wedding bath heritage; Leaves skin delicately scented with herbs',
    ingredients: 'Chickpea (Besan) Flour, Wild Turmeric (Curcuma aromatica), Neem Leaf Powder, Rose Petal Powder, Sandalwood Powder, Vetiver Root Powder.',
    how_to_use: 'Mix 2-3 tablespoons with rose water, milk, or plain water to make a smooth paste. Gently massage over damp skin, leave for 1-2 minutes, then rinse with water.',
    images: [
      '/images/products/herbal-ubtan-powder.jpg',
    ],
    rating: 4.8,
    review_count: 68,
  },
];

export const SEED_REVIEWS: Review[] = [
  {
    id: 'r1',
    product_id: 'p1111111-1111-1111-1111-111111111111',
    customer_name: 'Priya Sharma',
    rating: 5,
    comment: 'The Neem & Tulsi soap is wonderful! It lathers so smoothly without making my skin dry. Smells fresh and authentically botanical.',
    verified_purchase: true,
    created_at: '2026-02-15T10:00:00Z',
  },
  {
    id: 'r2',
    product_id: 'p5555555-5555-5555-5555-555555555555',
    customer_name: 'Devika Nair',
    rating: 5,
    comment: 'This Amla & Bhringraj oil is a holy grail. My scalp feels so calm and nourished, and my hair feels noticeably softer after each pre-wash massage.',
    verified_purchase: true,
    created_at: '2026-02-18T14:30:00Z',
  },
  {
    id: 'r3',
    product_id: 'p2222222-2222-2222-2222-222222222222',
    customer_name: 'Ananya Iyer',
    rating: 5,
    comment: 'So soothing on sensitive skin! Does not leave my face feeling tight at all. Real aloe freshness with zero artificial perfume.',
    verified_purchase: true,
    created_at: '2026-02-20T09:15:00Z',
  },
  {
    id: 'r4',
    product_id: 'p3333333-3333-3333-3333-333333333333',
    customer_name: 'Rohan Mehta',
    rating: 5,
    comment: 'The sandalwood night cream is exceptional. Very rich yet absorbs quickly, waking up with hydrated and smooth skin every morning.',
    verified_purchase: true,
    created_at: '2026-02-22T16:45:00Z',
  },
  {
    id: 'r5',
    product_id: 'paaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',
    customer_name: 'Kavita Sundaram',
    rating: 5,
    comment: 'Purest cold-pressed coconut oil I have used. I use it for both hair conditioning and post-bath hydration. The natural fragrance is delightful.',
    verified_purchase: true,
    created_at: '2026-02-24T11:20:00Z',
  },
];
